### ISSUE TITLE
Install Error Ubuntu 16.04

### ISSUE THREAD

**Issue by jstraw4663** [aberg83/docker-server#1]
When I run the script initially I get these errors near the end.   

![screenshot 2016-10-14 at 5 51 50 pm](https://cloud.githubusercontent.com/assets/7302419/19404653/d7697820-923d-11e6-9fb9-8797a7b5dea2.png)

**Comment by andrewpong** [comment]
I had to create the directory for it to add the htpasswd files.

**Comment by jstraw4663** [comment]
Thank you that worked!
