### ISSUE TITLE
This site can’t be reached- ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by zjpleau** [aberg83/docker-server#4]
I can't browse to any of the app URLs after running the script. Getting the error "This site can’t be reached- ERR_CONNECTION_REFUSED".

Also when I run ocker-compose logs -f nginx I get:

```
:~/docker-server$ docker-compose logs -f nginx
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

Lastly, how can I completely remove/cleanup the installation from this so I can start over?

Thanks

**Comment by aberg83** [comment]
you need to logout and back in as your user to use docker. as for your connection issues, did you point your domain to your IP?

**Comment by aberg83** [comment]
You also need to wait long enough to let nginx generate the certificate and DH params.

**Comment by zjpleau** [comment]
I logged out/in, i rebooted, I definitely waited long enough. Yes my IP is set correctly. I ended up blowing away this config to start over.
