### ISSUE TITLE
Domain Configuration for script? -SOLVED

### ISSUE THREAD

**Issue by Phaymous** [aberg83/docker-server#6]
If I just want this to be accessible internally - using DNSMasq or some other alternative what would be the ideal setup? My nginx configuration is failing on generating a new certificate and I can't seem to figure out which way would be best to resolve this. Thanks

**Comment by aberg83** [comment]
You need to forward ports 80 and 443 on your router to point to the internal IP of your server for Let's Encrypt to generate the certificate. Your domain name A record needs to point to your public IP address.

**Comment by Phaymous** [comment]
Thanks. What changes do you think might be necessary to make it connect from a subdomain? Like accountname.ddns.net for example?

`using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 50-config: executing...
2048 bit DH parameters present
SUBDOMAINS entered, processing
Sub-domains processed are:  -d www.accountname.ddns.net
Generating new certificate
Failed authorization procedure. www.accountname.ddns.net (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: DNS problem: NXDOMAIN looking up A for www.`accountname.ddns.net, accountname.ddns.net (tls-sni-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Failed to connect to my.wan.ip.address:443 for TLS-SNI-01 challenge
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: www.accountname.ddns.net
   Type:   connection
   Detail: DNS problem: NXDOMAIN looking up A for
   www.accountname.ddns.net

   Detail: Failed to connect to my.wan.ip.address:443 for TLS-SNI-01
   challenge

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A record(s) for that domain
   contain(s) the right IP address. Additionally, please check that
   your computer has a publicly routable IP address and that no
   firewalls are preventing the server from communicating with the
   client. If you're using the webroot plugin, you should also verify
   that you are serving files from the webroot path you provided.
/var/run/s6/etc/cont-init.d/50-config: line 105: cd: /config/keys/letsencrypt: No such file or directory
[cont-init.d] 50-config: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...`

**Comment by aberg83** [comment]
The way I setup the script to create the letsencrypt docker
container is to use only TLD with the www subdomain. You can edit
the docker-compose.yml file that the script generates and add your
subdomain in place of www and correct your domain entry. Then
restart the nginx docker.

Andrew



On Sat, Nov 12, 2016, at 04:01 PM, Phaymous wrote:
> Thanks. What changes do you think might be necessary to make it
> connect from a subdomain? Like accountname.ddns.net for example?
> using keys found in /config/keys [cont-init.d] 30-keygen: exited 0.
> [cont-init.d] 50-config: executing... 2048 bit DH parameters present
> SUBDOMAINS entered, processing Sub-domains processed are:  -d
> www.accountname.ddns.net Generating new certificate Failed
> authorization procedure. www.accountname.ddns.net (tls-sni-01):
> urn:acme:error:connection :: The server could not connect to the
> client to verify the domain :: DNS problem: NXDOMAIN looking up A for
> www.accountname.ddns.net, accountname.ddns.net (tls-sni-01):
> urn:acme:error:connection :: The server could not connect to the
> client to verify the domain :: Failed to connect to
> my.wan.ip.address:443 for TLS-SNI-01 challenge
>  IMPORTANT NOTES:


>  * The following errors were reported by the server:


> Domain: www.accountname.ddns.net Type:   connection Detail: DNS
> problem: NXDOMAIN looking up A for www.accountname.ddns.net


> Detail: Failed to connect to my.wan.ip.address:443 for TLS-SNI-01
> challenge


> To fix these errors, please make sure that your domain name was
> entered correctly and the DNS A record(s) for that domain contain(s)
> the right IP address. Additionally, please check that your computer
> has a publicly routable IP address and that no firewalls are
> preventing the server from communicating with the client. If you're
> using the webroot plugin, you should also verify that you are serving
> files from the webroot path you provided. /var/run/s6/etc/cont-init.d/50-
> config: line 105: cd: /config/keys/letsencrypt: No such file or
> directory [cont-init.d] 50-config: exited 1. [cont-finish.d] executing
> container finish scripts... [cont-finish.d] done. [s6-finish] syncing
> disks. [s6-finish] sending all processes the TERM signal. [s6-finish]
> sending all processes the KILL signal and exiting. [s6-init] making
> user provided files available at /var/run/s6/etc...exited 0. [s6-init]
> ensuring user provided files have correct perms...exited 0. [fix-
> attrs.d] applying ownership & permissions fixes... [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts... [cont-
> init.d] 10-adduser: executing...`
> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].
>


Links:

  1. https://github.com/aberg83/docker-server/issues/6#issuecomment-260148123

**Comment by Phaymous** [comment]
Interesting. I believe I did that, see my second comment. I managed to remove the www and it's still failing. I've got my router configured as you suggested, as well. Pinging that address successfully responds with my WAN IP, etc.

**Comment by Phaymous** [comment]
Solved my problems! Thanks for your help!
Now to just figure out the remaining pieces...
